/*
Couchbase Public API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package couchbasecapella

import (
	"encoding/json"
	"fmt"
)

// V3ClusterStatus the model 'V3ClusterStatus'
type V3ClusterStatus string

// List of v3ClusterStatus
const (
	V3CLUSTERSTATUS_DRAFT V3ClusterStatus = "draft"
	V3CLUSTERSTATUS_DEPLOYING V3ClusterStatus = "deploying"
	V3CLUSTERSTATUS_SCALING V3ClusterStatus = "scaling"
	V3CLUSTERSTATUS_UPGRADING V3ClusterStatus = "upgrading"
	V3CLUSTERSTATUS_REBALANCING V3ClusterStatus = "rebalancing"
	V3CLUSTERSTATUS_PEERING V3ClusterStatus = "peering"
	V3CLUSTERSTATUS_DESTROYING V3ClusterStatus = "destroying"
	V3CLUSTERSTATUS_HEALTHY V3ClusterStatus = "healthy"
	V3CLUSTERSTATUS_DEGRADED V3ClusterStatus = "degraded"
	V3CLUSTERSTATUS_DEPLOYMENT_FAILED V3ClusterStatus = "deploymentFailed"
	V3CLUSTERSTATUS_SCALE_FAILED V3ClusterStatus = "scaleFailed"
	V3CLUSTERSTATUS_UPGRADE_FAILED V3ClusterStatus = "upgradeFailed"
	V3CLUSTERSTATUS_REBALANCE_FAILED V3ClusterStatus = "rebalanceFailed"
	V3CLUSTERSTATUS_PEERING_FAILED V3ClusterStatus = "peeringFailed"
	V3CLUSTERSTATUS_DESTROY_FAILED V3ClusterStatus = "destroyFailed"
)

var allowedV3ClusterStatusEnumValues = []V3ClusterStatus{
	"draft",
	"deploying",
	"scaling",
	"upgrading",
	"rebalancing",
	"peering",
	"destroying",
	"healthy",
	"degraded",
	"deploymentFailed",
	"scaleFailed",
	"upgradeFailed",
	"rebalanceFailed",
	"peeringFailed",
	"destroyFailed",
}

func (v *V3ClusterStatus) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := V3ClusterStatus(value)
	for _, existing := range allowedV3ClusterStatusEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid V3ClusterStatus", value)
}

// NewV3ClusterStatusFromValue returns a pointer to a valid V3ClusterStatus
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewV3ClusterStatusFromValue(v string) (*V3ClusterStatus, error) {
	ev := V3ClusterStatus(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for V3ClusterStatus: valid values are %v", v, allowedV3ClusterStatusEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v V3ClusterStatus) IsValid() bool {
	for _, existing := range allowedV3ClusterStatusEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to v3ClusterStatus value
func (v V3ClusterStatus) Ptr() *V3ClusterStatus {
	return &v
}

type NullableV3ClusterStatus struct {
	value *V3ClusterStatus
	isSet bool
}

func (v NullableV3ClusterStatus) Get() *V3ClusterStatus {
	return v.value
}

func (v *NullableV3ClusterStatus) Set(val *V3ClusterStatus) {
	v.value = val
	v.isSet = true
}

func (v NullableV3ClusterStatus) IsSet() bool {
	return v.isSet
}

func (v *NullableV3ClusterStatus) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV3ClusterStatus(val *V3ClusterStatus) *NullableV3ClusterStatus {
	return &NullableV3ClusterStatus{value: val, isSet: true}
}

func (v NullableV3ClusterStatus) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV3ClusterStatus) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

