/*
Couchbase Public API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package couchbasecapella

import (
	"encoding/json"
)

// V3CreateClusterUserRequest struct for V3CreateClusterUserRequest
type V3CreateClusterUserRequest struct {
	Username string `json:"username"`
	Password string `json:"password"`
	AllBucketsAccess *V3BucketRoles `json:"allBucketsAccess,omitempty"`
	Buckets *[]V3CreateClusterUserRequestBuckets `json:"buckets,omitempty"`
}

// NewV3CreateClusterUserRequest instantiates a new V3CreateClusterUserRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewV3CreateClusterUserRequest(username string, password string) *V3CreateClusterUserRequest {
	this := V3CreateClusterUserRequest{}
	this.Username = username
	this.Password = password
	return &this
}

// NewV3CreateClusterUserRequestWithDefaults instantiates a new V3CreateClusterUserRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewV3CreateClusterUserRequestWithDefaults() *V3CreateClusterUserRequest {
	this := V3CreateClusterUserRequest{}
	return &this
}

// GetUsername returns the Username field value
func (o *V3CreateClusterUserRequest) GetUsername() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Username
}

// GetUsernameOk returns a tuple with the Username field value
// and a boolean to check if the value has been set.
func (o *V3CreateClusterUserRequest) GetUsernameOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Username, true
}

// SetUsername sets field value
func (o *V3CreateClusterUserRequest) SetUsername(v string) {
	o.Username = v
}

// GetPassword returns the Password field value
func (o *V3CreateClusterUserRequest) GetPassword() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Password
}

// GetPasswordOk returns a tuple with the Password field value
// and a boolean to check if the value has been set.
func (o *V3CreateClusterUserRequest) GetPasswordOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Password, true
}

// SetPassword sets field value
func (o *V3CreateClusterUserRequest) SetPassword(v string) {
	o.Password = v
}

// GetAllBucketsAccess returns the AllBucketsAccess field value if set, zero value otherwise.
func (o *V3CreateClusterUserRequest) GetAllBucketsAccess() V3BucketRoles {
	if o == nil || o.AllBucketsAccess == nil {
		var ret V3BucketRoles
		return ret
	}
	return *o.AllBucketsAccess
}

// GetAllBucketsAccessOk returns a tuple with the AllBucketsAccess field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V3CreateClusterUserRequest) GetAllBucketsAccessOk() (*V3BucketRoles, bool) {
	if o == nil || o.AllBucketsAccess == nil {
		return nil, false
	}
	return o.AllBucketsAccess, true
}

// HasAllBucketsAccess returns a boolean if a field has been set.
func (o *V3CreateClusterUserRequest) HasAllBucketsAccess() bool {
	if o != nil && o.AllBucketsAccess != nil {
		return true
	}

	return false
}

// SetAllBucketsAccess gets a reference to the given V3BucketRoles and assigns it to the AllBucketsAccess field.
func (o *V3CreateClusterUserRequest) SetAllBucketsAccess(v V3BucketRoles) {
	o.AllBucketsAccess = &v
}

// GetBuckets returns the Buckets field value if set, zero value otherwise.
func (o *V3CreateClusterUserRequest) GetBuckets() []V3CreateClusterUserRequestBuckets {
	if o == nil || o.Buckets == nil {
		var ret []V3CreateClusterUserRequestBuckets
		return ret
	}
	return *o.Buckets
}

// GetBucketsOk returns a tuple with the Buckets field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *V3CreateClusterUserRequest) GetBucketsOk() (*[]V3CreateClusterUserRequestBuckets, bool) {
	if o == nil || o.Buckets == nil {
		return nil, false
	}
	return o.Buckets, true
}

// HasBuckets returns a boolean if a field has been set.
func (o *V3CreateClusterUserRequest) HasBuckets() bool {
	if o != nil && o.Buckets != nil {
		return true
	}

	return false
}

// SetBuckets gets a reference to the given []V3CreateClusterUserRequestBuckets and assigns it to the Buckets field.
func (o *V3CreateClusterUserRequest) SetBuckets(v []V3CreateClusterUserRequestBuckets) {
	o.Buckets = &v
}

func (o V3CreateClusterUserRequest) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["username"] = o.Username
	}
	if true {
		toSerialize["password"] = o.Password
	}
	if o.AllBucketsAccess != nil {
		toSerialize["allBucketsAccess"] = o.AllBucketsAccess
	}
	if o.Buckets != nil {
		toSerialize["buckets"] = o.Buckets
	}
	return json.Marshal(toSerialize)
}

type NullableV3CreateClusterUserRequest struct {
	value *V3CreateClusterUserRequest
	isSet bool
}

func (v NullableV3CreateClusterUserRequest) Get() *V3CreateClusterUserRequest {
	return v.value
}

func (v *NullableV3CreateClusterUserRequest) Set(val *V3CreateClusterUserRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableV3CreateClusterUserRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableV3CreateClusterUserRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV3CreateClusterUserRequest(val *V3CreateClusterUserRequest) *NullableV3CreateClusterUserRequest {
	return &NullableV3CreateClusterUserRequest{value: val, isSet: true}
}

func (v NullableV3CreateClusterUserRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV3CreateClusterUserRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


