/*
Couchbase Public API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package couchbasecapella

import (
	"encoding/json"
)

// UpdateBucketRequest struct for UpdateBucketRequest
type UpdateBucketRequest struct {
	MemoryQuota int32 `json:"memoryQuota"`
}

// NewUpdateBucketRequest instantiates a new UpdateBucketRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewUpdateBucketRequest(memoryQuota int32) *UpdateBucketRequest {
	this := UpdateBucketRequest{}
	this.MemoryQuota = memoryQuota
	return &this
}

// NewUpdateBucketRequestWithDefaults instantiates a new UpdateBucketRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewUpdateBucketRequestWithDefaults() *UpdateBucketRequest {
	this := UpdateBucketRequest{}
	return &this
}

// GetMemoryQuota returns the MemoryQuota field value
func (o *UpdateBucketRequest) GetMemoryQuota() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.MemoryQuota
}

// GetMemoryQuotaOk returns a tuple with the MemoryQuota field value
// and a boolean to check if the value has been set.
func (o *UpdateBucketRequest) GetMemoryQuotaOk() (*int32, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.MemoryQuota, true
}

// SetMemoryQuota sets field value
func (o *UpdateBucketRequest) SetMemoryQuota(v int32) {
	o.MemoryQuota = v
}

func (o UpdateBucketRequest) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["memoryQuota"] = o.MemoryQuota
	}
	return json.Marshal(toSerialize)
}

type NullableUpdateBucketRequest struct {
	value *UpdateBucketRequest
	isSet bool
}

func (v NullableUpdateBucketRequest) Get() *UpdateBucketRequest {
	return v.value
}

func (v *NullableUpdateBucketRequest) Set(val *UpdateBucketRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableUpdateBucketRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableUpdateBucketRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableUpdateBucketRequest(val *UpdateBucketRequest) *NullableUpdateBucketRequest {
	return &NullableUpdateBucketRequest{value: val, isSet: true}
}

func (v NullableUpdateBucketRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableUpdateBucketRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


