/*
Couchbase Public API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package couchbasecloud

import (
	"encoding/json"
)

// ClusterVersion struct for ClusterVersion
type ClusterVersion struct {
	Name string `json:"name"`
	Components map[string]string `json:"components"`
}

// NewClusterVersion instantiates a new ClusterVersion object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewClusterVersion(name string, components map[string]string) *ClusterVersion {
	this := ClusterVersion{}
	this.Name = name
	this.Components = components
	return &this
}

// NewClusterVersionWithDefaults instantiates a new ClusterVersion object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewClusterVersionWithDefaults() *ClusterVersion {
	this := ClusterVersion{}
	return &this
}

// GetName returns the Name field value
func (o *ClusterVersion) GetName() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Name
}

// GetNameOk returns a tuple with the Name field value
// and a boolean to check if the value has been set.
func (o *ClusterVersion) GetNameOk() (*string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Name, true
}

// SetName sets field value
func (o *ClusterVersion) SetName(v string) {
	o.Name = v
}

// GetComponents returns the Components field value
func (o *ClusterVersion) GetComponents() map[string]string {
	if o == nil {
		var ret map[string]string
		return ret
	}

	return o.Components
}

// GetComponentsOk returns a tuple with the Components field value
// and a boolean to check if the value has been set.
func (o *ClusterVersion) GetComponentsOk() (*map[string]string, bool) {
	if o == nil  {
		return nil, false
	}
	return &o.Components, true
}

// SetComponents sets field value
func (o *ClusterVersion) SetComponents(v map[string]string) {
	o.Components = v
}

func (o ClusterVersion) MarshalJSON() ([]byte, error) {
	toSerialize := map[string]interface{}{}
	if true {
		toSerialize["name"] = o.Name
	}
	if true {
		toSerialize["components"] = o.Components
	}
	return json.Marshal(toSerialize)
}

type NullableClusterVersion struct {
	value *ClusterVersion
	isSet bool
}

func (v NullableClusterVersion) Get() *ClusterVersion {
	return v.value
}

func (v *NullableClusterVersion) Set(val *ClusterVersion) {
	v.value = val
	v.isSet = true
}

func (v NullableClusterVersion) IsSet() bool {
	return v.isSet
}

func (v *NullableClusterVersion) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableClusterVersion(val *ClusterVersion) *NullableClusterVersion {
	return &NullableClusterVersion{value: val, isSet: true}
}

func (v NullableClusterVersion) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableClusterVersion) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}


