/*
Couchbase Public API

No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)

API version: 2.0.0
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package couchbasecapella

import (
	"encoding/json"
	"fmt"
)

// V3Environment the model 'V3Environment'
type V3Environment string

// List of v3Environment
const (
	V3ENVIRONMENT_HOSTED V3Environment = "hosted"
	V3ENVIRONMENT_VPC V3Environment = "vpc"
)

var allowedV3EnvironmentEnumValues = []V3Environment{
	"hosted",
	"vpc",
}

func (v *V3Environment) UnmarshalJSON(src []byte) error {
	var value string
	err := json.Unmarshal(src, &value)
	if err != nil {
		return err
	}
	enumTypeValue := V3Environment(value)
	for _, existing := range allowedV3EnvironmentEnumValues {
		if existing == enumTypeValue {
			*v = enumTypeValue
			return nil
		}
	}

	return fmt.Errorf("%+v is not a valid V3Environment", value)
}

// NewV3EnvironmentFromValue returns a pointer to a valid V3Environment
// for the value passed as argument, or an error if the value passed is not allowed by the enum
func NewV3EnvironmentFromValue(v string) (*V3Environment, error) {
	ev := V3Environment(v)
	if ev.IsValid() {
		return &ev, nil
	} else {
		return nil, fmt.Errorf("invalid value '%v' for V3Environment: valid values are %v", v, allowedV3EnvironmentEnumValues)
	}
}

// IsValid return true if the value is valid for the enum, false otherwise
func (v V3Environment) IsValid() bool {
	for _, existing := range allowedV3EnvironmentEnumValues {
		if existing == v {
			return true
		}
	}
	return false
}

// Ptr returns reference to v3Environment value
func (v V3Environment) Ptr() *V3Environment {
	return &v
}

type NullableV3Environment struct {
	value *V3Environment
	isSet bool
}

func (v NullableV3Environment) Get() *V3Environment {
	return v.value
}

func (v *NullableV3Environment) Set(val *V3Environment) {
	v.value = val
	v.isSet = true
}

func (v NullableV3Environment) IsSet() bool {
	return v.isSet
}

func (v *NullableV3Environment) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableV3Environment(val *V3Environment) *NullableV3Environment {
	return &NullableV3Environment{value: val, isSet: true}
}

func (v NullableV3Environment) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableV3Environment) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}

